<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Fix a-zA-Z0-9_ vs \p{Alnum} et al according to Oniguruma syntax</string>
	<key>fileTypes</key>
	<array>
		<string>calvin</string>
	</array>
	<key>name</key>
	<string>CalvinScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#constdef</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#component</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#instance</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#connection</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
			</array>
		</dict>
		<key>block_compdef</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docstring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#instance</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#connection</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#connection_inport_proxy</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#connection_outport_proxy</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_shebang</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line_deprecated</string>
				</dict>
			</array>
		</dict>
		<key>comment_block</key>
		<dict>
			<key>begin</key>
			<string>\s*/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>begin</key>
			<string>\s*#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<key>comment_line_deprecated</key>
		<dict>
			<key>begin</key>
			<string>\s*//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<key>comment_shebang</key>
		<dict>
			<key>begin</key>
			<string>^#!</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign.shebang</string>
		</dict>
		<key>comp_signature_def</key>
		<dict>
			<key>begin</key>
			<string>([\p{Alpha}_][\p{Alnum}_]*)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Can I use lookahead to end in order not to consume? Yes.</string>
			<key>end</key>
			<string>(?=\))</string>
			<key>name</key>
			<string>meta.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
		</dict>
		<key>component</key>
		<dict>
			<key>begin</key>
			<string>^\s*(component)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>How can I run patterns inside of the beginCapture? Not possible.</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comp_signature_def</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#port_def</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_compdef</string>
				</dict>
			</array>
		</dict>
		<key>connection</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.calvin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other.calvin</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([\p{Alpha}_][\p{Alnum}_]*)\.([\p{Alpha}_][\p{Alnum}_]*)\s*(&gt;)\s*([\p{Alpha}_][\p{Alnum}_]*)\.([\p{Alpha}_][\p{Alnum}_]*)\s*$</string>
		</dict>
		<key>connection_inport_proxy</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.decorator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.calvin</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>aliased inport</string>
			<key>match</key>
			<string>^\s*(\.[\p{Alpha}_][\p{Alnum}_]*)\s*(&gt;)\s*([\p{Alpha}_][\p{Alnum}_]*)\.([\p{Alpha}_][\p{Alnum}_]*)\s*$</string>
		</dict>
		<key>connection_outport_proxy</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.calvin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.decorator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>aliased outport</string>
			<key>match</key>
			<string>^\s*([\p{Alpha}_][\p{Alnum}_]*)\.([\p{Alpha}_][\p{Alnum}_]*)\s*(&gt;)\s*(\.[\p{Alpha}_][\p{Alnum}_]*)\s*$</string>
		</dict>
		<key>constdef</key>
		<dict>
			<key>begin</key>
			<string>^\s*(define)\s+([\p{Alpha}_][\p{Alnum}_]*)\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<key>docstring</key>
		<dict>
			<key>begin</key>
			<string>\s*"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.quoted.triple</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>instance</key>
		<dict>
			<key>begin</key>
			<string>^\s*([\p{Alpha}_][\p{Alnum}_]*)\s*(:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.calvin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#qualified_actor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#named_param</string>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>\S.*</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<key>named_param</key>
		<dict>
			<key>begin</key>
			<string>([\p{Alpha}_][\p{Alnum}_]*)\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(,|(?=\)))</string>
			<key>name</key>
			<string>meta.function-call.arguments</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>[0-9]+(?:\.[0-9]*)?</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>parameter</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*([A-Za-z_][A-Za-z0-9_]*)\s*</string>
		</dict>
		<key>port_def</key>
		<dict>
			<key>begin</key>
			<string>\)</string>
			<key>end</key>
			<string>\{</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#portname</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-&gt;</string>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</array>
		</dict>
		<key>portname</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.decorator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*([A-Za-z_][A-Za-z0-9_]*)\s*</string>
		</dict>
		<key>qualified_actor</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.calvin</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class.calvin</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(((?:[\p{Alpha}_][\p{Alnum}_]*\.)*)([\p{Alpha}_][\p{Alnum}_]*))\s*\(</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
		<key>string_raw</key>
		<dict>
			<key>begin</key>
			<string>!"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.raw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*([A-Za-z_][A-Za-z0-9_]*)\s*</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.calvin</string>
	<key>uuid</key>
	<string>EF67D759-EB8D-4092-9641-B0E97A93AF7F</string>
</dict>
</plist>
